/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Complicated.Calculator;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.BorderLayout;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        JFrame frame = new JFrame("My First Frame");
        // Set the default close operation (what happens when the user clicks the 'X' button)
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Set the size of the frame
        frame.setSize(400, 300);

        JPanel panel = new JPanel();
        JButton button = new JButton("Click Me!");
        JLabel displayLabel = new JLabel("Welcome to the application!");

        panel.add(button);
        panel.add(displayLabel);
        frame.add(panel, BorderLayout.CENTER); // Add the panel to the center of the frame

        // Make the frame visible
        frame.setVisible(true);
    }
}
