/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Complicated.Calculator;

import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        Calculator calc = new Calculator(400, 300, "Complicated Calculator");
        JFrame frame = calc.getCalculatorFrame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
