/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Complicated.Calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testCalculatorFrameIsNotNull() {
        // Create a Calculator with the same dimensions/title used by App
        Calculator calc = new Calculator(400, 300, "Complicated Calculator");
        assertNotNull("Calculator should provide a non-null JFrame", calc.getCalculatorFrame());
    }
}
